### PR TITLE
Handle `in`, `out`, and `ref` parameters correctly

### PR DESCRIPTION
**Pull request by bert2**
Fixes two ~(maybe three)~ problems in case a parameter is passed with one of the modifiers `in`, `out`, or `ref`:

1. Resolving of nullable types breaks, because a parameter of type `ref Nullable<T>` is not considered generic. The `ref` (same as `in` and `out`) effectively "wraps" the `Nullable<T>` and has to be unwrapped with `GetElementType()` before checking for nullability.
2. Resolving of tuples breaks, for the same reason.
3. ~mddox generates duplicate type documentations in some cases. I think it happens when a type of the API is passed with `ref`, `in`, or `out`.  The default `Type.Name` value of a `ref` type is the `Name` of the element type with a `"&"` suffix. Because DocXml might report `ref` types like that, mddox creates two class documentations (e.g. one for `MyClass` and one for `MyClass&`). However, that's just an assumption and I didn't actually check this properly yet.~

### CODE REVIEW

**Comment by loxsmoke** [comment]
Nice improvement with one observation. Based on unit test  ToTypeNameString() does not return "in" and "ref" qualifiers. Would be good to have them in the output.

**Comment by bert2** [comment]
I agree, but I shied away from changing `ToNameString()` because its implementation looked complicated.

It was easy to check if `ToNameString()` gets a `ref` type and append the standard `&` suffix (`Type.IsByRef` is sufficient here). However, I requires a bit more restructuring to actually check whether it was an `in`, `out`, or `ref` parameter and prepend the appropriate modifier (only `PropertyInfo.IsIn/IsOut` can help here, but `ToNameString()` does not get the `PropertyInfo`).

What to you think about fixing the bug and adding `&` first? Replacing the generic `&` suffix with `in`, `out` and `ref` modifiers could be done in a separate PR.

Will add some more unit tests, as I now changed code that gets called for more things than just method parameters.

**Comment by loxsmoke** [comment]
There were multiple code changes and I did not know how to modify your pull request so I reworked your code into pull request #6

**Comment by bert2** [comment]
@loxsmoke I always allow maintainers to edit my pull requests. I think the easiest way to do this as a maintainer is to clone my fork and checkout the branch the PR is coming from. When you push your changes the PR will be updated automatically.
I guess you could also add my fork as a remote to your existing clone, but for small repos this shouldn't make much of a difference.

**Pull request closed without merging**
